// summit/src/components/Common/Footer.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import { SiLinktree } from 'react-icons/si';

const Footer = () => {
    return (
        <footer className="footer-area">
            <div className="container">
                <div className="row">
                    <div className="col-lg-6 col-md-6">
                        <div className="single-footer-widget">
                            <h3>Summit Information</h3>
                            <span>
                                <i className="icofont-calendar"></i> May 29 - May 31, 2024
                            </span>

                            <p className="location">
                                <i className="icofont-google-map"></i> Palace of Fine Arts, San Francisco, CA 94123
                            </p>
                            

                            <p className="location">
                                <i className="icofont-email"></i> genaix@gptdao.ai
                            </p>
                            
                            <a href="https://linktr.ee/gptdao" target="_blank" rel="noopener noreferrer" className="contact-authority">
                                <i className="icofont-phone"></i> Contact Us
                            </a>

                            
                        </div>
                    </div>

                    <div className="col-lg-6 col-md-6">
                        <div className="single-footer-widget">
                            <h3>Contact Us</h3>
                            <p>We sincerely invite you to join us, bring your creativity and ideals, and explore the future of generative AI together. Please contact us for more information about the Generative AI Summit San Francisco 2024.</p>
                            
                            <ul className="social-links">
                                <li>
                                    <Link to="https://linktr.ee/gptdao" className="twitter" target="_blank">
                                       <SiLinktree />
                                    </Link>
                                </li>
                                <li>
                                    <Link to="https://twitter.com/GPTDAOGLOBAL" className="twitter" target="_blank">
                                        <i className="icofont-twitter"></i>
                                    </Link>
                                </li>
                                <li>
                                    <Link to="https://www.linkedin.com/company/gptdao" className="linkedin" target="_blank">
                                        <i className="icofont-linkedin"></i>
                                    </Link>
                                </li>
                                <li>
                                    <Link to="https://www.gptdao.ai/" className="facebook" target="_blank">
                                        <i className="icofont-web"></i>
                                    </Link>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div className="col-lg-12">
                        <div className="copyright-area">
                            <p>
                                Copyright <i className="icofont-copyright"></i> 2024 GPTDAO. All rights reserved
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    );
}
 
export default Footer;

// summit/src/components/Footer.vue
<template>
  <div class="footer">
   <div class="info" :class="screenWidth > 600 ? '' : 'mb'">
      <div class="item">
       <div>
        <div class="title">Summit Information</div>
        <div class="list">May 29 - May 31, 2024</div>
        <div class="list">Palace of Fine Arts, San Francisco, CA 94123</div>
        <div class="list">genaix@gptdao.ai</div>
        <div class="list h" @click="openUrl('https://linktr.ee/gptdao')">Contact Us</div>
       </div>
      </div>
      <div class="item">
        <div>
          <div class="title">Contact Us</div>
          <div class="list">We sincerely invite you to join us, bring your creativity and ideals, and explore the future of generative AI together. Please contact us for more information about the Generative AI Summit San Francisco 2024.4</div>
          <div class="list">
            <img @click="openUrl('https://www.gptdao.ai/')" src="../assets/images/FB.png" alt="">
            <img @click="openUrl('https://twitter.com/GPTDAOGLOBAL')" src="../assets/images/IG.png" alt="">
            <img @click="openUrl('https://www.linkedin.cn/incareer/company/gptdao')" src="../assets/images/WA.png" alt="">
          </div>
        </div>
      </div>
   </div>
   <div class="bottom">
    Copyright  2024 GPTDAO. All rights reserved
   </div>
  </div>
</template>

<script>
import { ref, computed, watch } from 'vue';
import { useStore} from 'vuex'

export default {
  name: '',
  setup() {
    const store = useStore();

    const openUrl = (url) => {
      window.open(url)
    }
    //适配
    const screenWidth = computed(() => {
      return store.state.screenWidth;
    });
    return {
      openUrl,
      screenWidth
    } 
  },
  components: {
    
  },
  methods: {
    
  },
  mounted() {
    
  },
  unmounted() {
    
  },
}
</script>

<style scoped lang='scss'>
.footer{
  background: #000000;
  font-family: HarmonyOS Sans SC Regular;
  font-weight: 400;
  font-size: .296rem;
  color: rgba(255,255,255,.5);
  line-height: .46rem;
  text-align: left;
  font-style: normal;
  text-transform: none;
  padding: 0 0 .5rem;
  .info{
    display: flex;
    flex-wrap: wrap;
    width: 100%;
    margin: 0 auto;
    max-width: 1200px;
    padding: 0 .5rem;
    &.mb{
      .item{
        width: 100%;
      }
    }
    .item{
      width: 50%;
      display: flex;
      flex-direction: column;
      margin-top: 1rem;
      .title{
        font-family: HarmonyOS Sans SC Bold;
        font-weight: bold;
        font-size: 24px;
        color: #FFFFFF;
        line-height: 28px;
        text-align: left;
        font-style: normal;
        text-transform: none;
      }
      .list{
        margin-top: .2rem;

        &.h{
          cursor: pointer;
        }
        img{
          margin-right: .3rem;
          cursor: pointer;
        }
      }
    }
  }
  .bottom{
    font-family: HarmonyOS Sans SC Regular;
    font-weight: 400;
    font-size: .259rem;
    color: rgba(255,255,255,.5);
    line-height: .296rem;
    text-align: center;
    font-style: normal;
    text-transform: none;
    margin-top: .5rem;
    border-top: 1px solid rgba(255,255,255,.5);
    padding-top: .5rem;
  }
}
</style>
